prgrms-web-devcourse/Team_WAS_YAS_BE

.github/workflows/deploy.yml, src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java, src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCompletion.java, src/main/java/org/prgrms/yas/domain/user/domain/User.java
- 기본 엔티티 문자열 길이 수정
- 문자열 길이를 여유공간을 포함해서 할당하도록 length 옵션 변경
- User 엔티티 -> UserPost 엔티티와 연관관계 할당
=> 기본 엔티티 문자열 길이 수정

.gitignore, build.gradle, src/main/java/org/prgrms/yas/configures/OpenApiConfig.java, src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/domain/User.java
Swagger 설정 추가
- Swagger 의존성 추가
- Swagger/OpenAPI Config 파일 작성
- 패키지 정리 및 칼럼명 수정
=> feat : Swagger/OpenAPI 설정 추가

src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java, src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
미션 삭제기능 추가 
미션 삭제시 is_deleted를 통해 soft delete 진행
=> feat : #38/Mission 삭제 기능 추가 

build.gradle, src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java, src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/domain/User.java, src/main/java/org/prgrms/yas/domain/user/dto/UserUpdateRequest.java, src/main/java/org/prgrms/yas/domain/user/exception/IllegalFileException.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java, src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
회원가입기능 추가
- 기본적인 회원가입 기능 구현
- 예외처리 기능 구현
- S3 버킷과 연동
- DB와 비교하여 S3 파일 삭제구현은 추후 리팩토링 예정
Closes #11
=> feat : 회원가입 기능

src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/domain/User.java, src/main/java/org/prgrms/yas/domain/user/dto/UserResponse.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java
회원조회 기능 추가
- 기본적인 회원조회 기능 구현
- 응답객체에서 id 제거
Closes #49
=> feat : 회원조회 기능

src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java, src/test/java/org/prgrms/yas/domain/routine/service/RoutineServiceTest.java
미션 전체 조회 기능 추가 
루틴아이디를 통해 아이디에 맞는 루틴들 조회 가능
=> feat : #41/미션 전체 조회 기능 추가 

appspec.yml
appsepc.yml 작성
- appsepc.yml 작성
=> feat : appsepc.yml 작성

appspec.yml
appsepc.yml 작성
- appsepc.yml 작성
=> Chore : appsepc.yml 작성

src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java, src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionOrder.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionUpdateRequest.java, src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
미션을 수정 할 수 있다. 
미션에 대한 순서를 받으면 수정 할 수 있다.
=> feat : #44/미션 수정 기능 추가 

appspec.yml, src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java
중괄호 삭제
- conflict resolve 간에 발새한 중괄호 에러 해결
=> chore : 중괄호 삭제

appspec.yml
=> chore :  appspec.yml 수정

scripts/deploy.sh
=> Chore : 스크립트 파일 추가

build.gradle, scripts/deploy.sh, src/main/java/org/prgrms/yas/configures/OpenApiConfig.java, src/main/java/org/prgrms/yas/global/aws/S3Uploader.java, src/main/resources/application-local.yml
설정 파일 수정
- 스웨거 버전 변경에 따른 설정 파일 수정
- 배포 파일 스크립트 수정
=> refactor : 설정 파일 수정

build.gradle
빌드 파일 수정
- google.common 빌드 파일 수정
=> Chore : 빌드 파일 수정

src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java, src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java, src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/resources/application-local.yml
배포관련 버그 수정
- PK 전략 IDENTITY로 변경
- Jwt 파라미터 삭제를 위해 스웨거 어노테이션 추가
- 배포 관련 버그 해결을 위해 yml 파일 수정
=> fix : 배포관련 버그 수정

src/main/java/org/prgrms/yas/configures/WebConfig.java
Cors 설정 추가
- Cors 설정 추가
Closes #74
=> feat : #74/Cors 설정 추가

src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
=> feat : #74/CORS 에러 설정 추가

src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
=> Chore : WebSecurityConfig import 정리

src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/domain/User.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java
회원삭제기능 구현
- 회원 삭제 기능 구현
- @SQLDelete를 활용하여 삭제 구현
Closes #10
=> feat : #10/회원삭제기능 구현

src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java, src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/domain/User.java, src/main/java/org/prgrms/yas/domain/user/dto/UserSignUpRequest.java, src/main/java/org/prgrms/yas/domain/user/exception/NotSamePasswordException.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java, src/main/java/org/prgrms/yas/global/error/GlobalExceptionHandler.java, src/main/java/org/prgrms/yas/global/exception/NotFoundException.java
회원 프로필 사진 버그 수정
- 회원 프로필 사진을 선택적으로 전송받을 수 있도록 변경
- 예외처리 네이밍 변경
Closes #71
=> refactor : #71/회원 프로필 사진 버그 수정

src/main/java/org/prgrms/yas/YasApplication.java, src/main/java/org/prgrms/yas/domain/BaseEntity.java, src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java, src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java, src/main/java/org/prgrms/yas/domain/comment/dto/CommentCreateRequest.java, src/main/java/org/prgrms/yas/domain/comment/dto/CommentUpdateRequest.java, src/main/java/org/prgrms/yas/domain/comment/exception/NotFoundCommentException.java, src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java, src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java, src/main/java/org/prgrms/yas/domain/post/controller/PostController.java, src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java, src/main/java/org/prgrms/yas/domain/post/dto/CategoryDto.java, src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java, src/main/java/org/prgrms/yas/domain/post/dto/MissionDto.java, src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java, src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java, src/main/java/org/prgrms/yas/domain/post/dto/UserDto.java, src/main/java/org/prgrms/yas/domain/post/exception/NotFoundRoutinePostException.java, src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java, src/main/java/org/prgrms/yas/domain/post/service/PostService.java
게시글/댓글 API
- 댓글 등록/삭제/수정
- 게시글 등록/삭제/단건조회
=> Feat : 게시글/댓글 API

src/main/java/org/prgrms/yas/domain/user/domain/User.java, src/main/java/org/prgrms/yas/domain/user/dto/UserResponse.java
회원조회 응답객체 수정
- 응답 객체에 id 추가
Closes #86
=> refactor : #86/회원조회 응답객체 수정

src/main/java/org/prgrms/yas/domain/mission/dto/MissionCreateRequest.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusUpdateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
=> Refactor : 시간 정규식 수정

src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
루틴 상세조회 반환객체에 weeks 추가
루틴 상세조회 반환객체에 weeks 추가
=> feat : #106/루틴 상세조회 반환객체에 weeks 추가

src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java, src/main/java/org/prgrms/yas/domain/mission/controller/MissionStatusController.java, src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
루틴,미션 스웨거 설정 추가
루틴,미션 스웨거 설정 추가
=> feat : #108/루틴,미션 스웨거 설정 추가

build.gradle, src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
CI/CD 수정
- S3 업로드 관련 이슈 해결
- 관련 CI/CD 코드 변경
=> fix : CI/CD 수정

src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java, src/main/java/org/prgrms/yas/domain/likes/domain/PostLikes.java, src/main/java/org/prgrms/yas/domain/likes/repsitory/PostLikesRepository.java, src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java, src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java, src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
게시물 좋아요 기능 구현
- 게시물 좋아요 생성 기능 구현
- 중복된 값은 1개의 데이터만 유지하도록 sql문 구현
- 게시물 좋아요 삭제 기능 구현
- 회원 아이디, 게시물 아이디를 이용해 삭제 구현
Closes #104
=> feat: #104/게시물 좋아요 기능 구현

src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java, src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java, src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java, src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java, src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
댓글좋아요 기능 구현
- 댓글 좋아요 생성 기능 구현
- 댓글 좋아요 삭제 기능 구현
Closes #112
=> feat : #112/댓글좋아요 기능 구현

src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java, src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java, src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java, src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java, src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java, src/main/java/org/prgrms/yas/domain/likes/dto/LikesDto.java, src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java, src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java, src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java, src/main/java/org/prgrms/yas/domain/post/controller/PostController.java, src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java, src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java, src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java, src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java, src/main/java/org/prgrms/yas/domain/post/service/PostService.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
게시글 조회 응답객체 변경
- 댓글 좋아요에 따른 단일 게시글 조회 응답객체 변경
- 응답객체에 댓글 추가
- 응답객체에 각 댓글 별 좋아요 누른 회원 추가
Closes #118
=> refactor : #118/게시글 조회 응답객체 변경

src/main/java/org/prgrms/yas/YasApplication.java
=> fix : #131/타임존 문제 해결

src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
루틴 카테고리 종류 추가.
루틴 카테고리 종류 추가
closed #130
=> refactor : #130/루틴 카테고리 종류 추가

src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java, src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java, src/main/java/org/prgrms/yas/domain/post/dto/WeekDto.java
응답객체 필드 추가
- color 필드 추가
- startGoalTime 필드 추가
=> Refactor : #139/응답객체 필드 추가

src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
RoutineController 수정
- Conflict 간 발생한 중복 코드 수정
=> fix : RoutineController 수정

src/main/java/org/prgrms/yas/domain/post/controller/PostController.java, src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
게시판에서 루틴 가져오기 기능 추가
- 게시판에서 루틴 가져오기 기능 추가
- 루틴과 미션을 한번에 저장하는 기능 
closed #142
=> feat : #142/게시판에서 루틴 가져오기 기능 추가

src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
루틴 조회시 삭제된 데이터 조회 안되게 변경
루틴 조회시 삭제된 데이터 조회 안되게 변경
=> feat : #147/루틴 조회시 삭제된 데이터 조회 안되게 변경

src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
루틴 상세 조회시 미션 수정
미션에서 삭제된 값 가져오는 오류 해결
=> feat : #153/루틴 상세 조회시 미션 수정

src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
타임존 시간 수정
- 일단, LocalDateTime 메소드를 통해 시간 수정
- 추후, 리팩토링 예정(필수)
Closes #157
=> Fix : 타임존 시간 수정

src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusDetailResponse.java
미션 상태 조회시 응답객체에 userDurationTime 추가
미션 상태 조회시 응답객체에 userDurationTime 추가
=> feat : #168/ 미션 상태 조회시 응답객체에 userDurationTime 추가

src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java, src/main/java/org/prgrms/yas/domain/post/service/PostService.java
게시물 단건조회의 응답객체 변경
- 게시물 단건조회 응답객체에서 좋아요 정보 추가
Closes #167
=> Fix : 게시물 단건조회의 응답객체 변경

src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java, src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java, src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java
좋아요 로직 수정
- 다른 사람의 댓글을 좋아요 추가할 수 있도록 로직 수정
- 다른 사람의 게시물을 좋아요 추가할 수 있도록 로직 수정
Closes #165
=> fix : #165/좋아요 로직 수정

src/main/java/org/prgrms/yas/domain/post/dto/PostCreateRequest.java
게시물 생성 DTO 수정
- 기본 생성자 추가
Closes #173
=> fix : #173/게시물 생성 DTO 수정

src/main/java/org/prgrms/yas/domain/post/service/PostService.java
게시물 삭제 메소드 수정
- 게시물 삭제 트랜젝션 내부에서 삭제 두번 실행 수정
- 삭제 메소드 하나 삭제
Closes #176
=> Fix : 게시물 삭제 메소드 수정

src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
게시글 조회시 중복되는 값 제거
- 인기글 조회시 중복 제거
=> feat : #179/게시글 조회시 중복되는 값 제거

src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java, src/main/java/org/prgrms/yas/domain/post/service/PostService.java
게시물 조회시 중복되는 문제 해결
인기 게시물 조회시 중복되는 문제 해결
=> fix : 게시물 조회시 중복되는 문제 해결

src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
게시물 단건 조회시 응답객체에 필드 추가
- 루틴에 color,startGoalTime,weeks 추가
=> feat : #182/게시물 단건 조회시 응답객체에 필드 추가

src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java, src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
게시물 단건 조회시 응답객체에 필드 추가
- color, weeks, startGoalTime 추가
=> refactor : 게시물 단건 조회시 응답객체에 필드 추가

src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java, src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java, src/main/java/org/prgrms/yas/domain/post/service/PostService.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
루틴조회시 반환객체에 포스팅되었는지 확인하는 필드 추가
- Routine 테이블에 is_posted 컬럼 추가
- 각각의 루틴 조회 반환객체에  추가
- 해당 루틴이 게시물에 올라가있을경우 is_posted 는 true  게시물을 삭제했을 경우엔 False로 세팅
=> refactor : #184/루틴조회시 반환객체에 포스팅되었는지 확인하는 필드 추가

src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java, src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java, src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java, src/main/java/org/prgrms/yas/domain/post/service/PostService.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
루틴조회시 반환객체에 포스팅되었는지 확인하는 필드 추가
루틴조회시 반환객체에 포스팅되었는지 확인하는 필드 추가
=> refactor : 루틴조회시 반환객체에 포스팅되었는지 확인하는 필드 추가

src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
게시판에서 루틴 가져올때 오류 해결
-Get -> post
=> feat : #188/게시판에서 루틴 가져올때 오류 해결

src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
미션 순서 변경시 생기는 오류 수정
레포지토리에서 찾아올때 Routine이 아닌 routineId로 찾아오게 변경
=> fix : #191/미션 순서 변경시 생기는 오류 수정

src/main/resources/application-local.yml
jwt 토큰 유효시간 변경
- jwt 토큰 유효시간을 24시간으로 변경
Closes #195
=> chore : #195/jwt 토큰 유효시간 변경

src/main/java/org/prgrms/yas/domain/post/service/PostService.java
삭제된 게시물 조회 수정
- 삭제되지 않은 게시물만 조회될 수 있도록 변경
Closes #197
=> fix : 삭제된 게시물 조회 수정

appspec.yml, scripts/health_check.sh, scripts/run_new_was.sh, scripts/switch.sh
nginx 스크립트 추가
- 무중단 배포 스크립트 추가
=> Fix : nginx 스크립트 추가

src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
=> Test : nginx 서버 실행 확인

src/main/java/org/prgrms/yas/domain/user/controller/TestController.java, src/main/resources/application-local.yml
=> Chore : Nginx 테스트 위한 컨트롤러 생성

src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
삭제된 게시물 조회 에러 수정
- 조회할 때 삭제된 게시물 조회되는 에러 수정
Closes #200
=> Fix : #200/삭제된 게시물 조회 에러 수정

src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java, src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionCreateRequest.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusDetailResponse.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusUpdateRequest.java, src/main/java/org/prgrms/yas/domain/post/controller/PostController.java, src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java, src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java, src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java, src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java, src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java
시간 타입 관련 메소드 수정
- 임시방편으로 timezone 메소드 수정 -> 이후 리팩토링 예정
Closes #203
=> fix : 시간 타입 관련 메소드 수정

src/main/java/org/prgrms/yas/domain/BaseEntity.java, src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusDetailResponse.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusUpdateRequest.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java, src/main/java/org/prgrms/yas/domain/post/controller/PostController.java, src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java, src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java, src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java, src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java, src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java, src/main/java/org/prgrms/yas/domain/routine/service/Status.java
타임존 문제 해결
LocalDateTime -> ZonedDateTime 으로 변경
=> fix : #212/타임존 문제 해결

src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java, src/main/java/org/prgrms/yas/domain/BaseEntity.java, src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusDetailResponse.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusUpdateRequest.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java, src/main/java/org/prgrms/yas/domain/post/controller/PostController.java, src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java, src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java, src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java, src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java, src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java, src/main/java/org/prgrms/yas/domain/routine/service/Status.java, src/main/resources/application.yml
타임존 문제 해결
LocalDatetime -> ZoneDatetime
=> fix : #develop/타임존 문제 해결

src/main/java/org/prgrms/yas/YasApplication.java, src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
BaseEntity 시간 에러 수정
- ZoneDateTime과 타입 에러 수정
- EnableJpaAuditing에 옵션을 주어 해결
=> Fix : BaseEntity 시간 에러 수정

README.md
=> style : readme 수정 

src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
=> refactor : #226/ 카테고리 종류 추가

src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
Calendar 클래스 타임존 변경
- Calendar 타임존 변경
- 한국시간으로 변경
Closes #230
=> Fix : #230/Calendar 클래스 타임존 변경

src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
Calendar 타임존 변경
- Calendar 타임존 변경
- 한국시간으로 변경
=> fix : Calendar 타임존 변경

src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java, src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
게시물 삭제간 댓글로 인한 에러 해결
- 게시물 삭제과정에서 댓글과의 연관관계로 인해 삭제 오류 해결
- 삭제 방식변경
Closes #234
=> hotfix : #234/게시물 삭제간 댓글로 인한 에러 해결

src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java, src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
게시물 삭제간 에러 해결
- 게시물 삭제과정에서 댓글과의 연관관계로 인해 삭제 오류 해결
- 삭제 방식변경
=> Hotfix : 게시물 삭제간 에러 해결

src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java, src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java, src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java, src/main/java/org/prgrms/yas/domain/post/service/PostService.java
댓글 좋아요와 게시물 관계 수정
- 게시물 삭제 간 연관관계로 인한 에러 수정
=> Hotfix : 댓글 좋아요와 게시물 관계 수정

build.gradle, src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java, src/main/java/org/prgrms/yas/oauth2/CookieUtil.java, src/main/java/org/prgrms/yas/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java, src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java, src/main/resources/application-prod.yml
- 소셜 로그인 기능 추가
- 카카오 소셜 로그인 기능 추가
- gradle 수정
- 카카오 yml 파일 수정
- WebConfig파일 수정
- 카카오 로그인 기능 추가
Closes #240
=> feat : #240/카카오 소셜로그인 기능 추가

src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
=> Chore : 브랜치 동기화

src/main/resources/application-prod.yml
- 소셜 로그인 리다이렉트 주소 수정
- 카카오 소셜 로그인 리다이렉트 주소 설정 수정
Closes #246
=> fix : #246/소셜 로그인 리다이렉트 주소 수정

README.md
=> deploy : 소셜 로그인 리다이렉트 주소 수정 후 배포

src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/dto/UserEmailRequest.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java
회원가입시 이메일 중복 체크 기능 추가
- Boolean을 이용하여 회원가입시 이메일 중복 체크 응답 기능 추가
Closes #253
=> feat : #253/회원가입시 이메일 중복 체크 기능 추가

src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/domain/User.java, src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java
회원 비밀번호 변경 기능 추가
- 회원 비밀번호 변경 기능 추가
- 기존의 비밀번호와 일치 여부 확인
- 비밀번호 확인 문자열과 일치하는 지 확인
Closes #251
=> feat : #251/회원 비밀번호 변경 기능 추가

src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
- 회원컨트롤러 충돌 해결
- 기존의 회원 컨트롤러 충돌 간 발생한 문제 해결
=> Fix : 회원컨트롤러 충돌 해결

src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/dto/UserToken.java, src/main/java/org/prgrms/yas/jwt/Jwt.java, src/main/java/org/prgrms/yas/jwt/JwtAuthentication.java, src/main/java/org/prgrms/yas/jwt/JwtAuthenticationFilter.java, src/main/java/org/prgrms/yas/jwt/JwtAuthenticationProvider.java, src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java
JWT 토큰 구조 변경
- 로그인 이슈 해결
- JWT 토큰 이메일 필드 삭제
Closes #258
=> refactor : #258/JWT 토큰 구조 변경

src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
- WebSecurityConfig 설정 추가
- 이메일 중복 체크 URL 설정 추가
=> refactor : #261/WebSecurityConfig 설정 추가

src/main/java/org/prgrms/yas/domain/user/service/UserService.java
- 소셜로그인 시 회원가입 데이터 수정
- 소셜로그인 시 회원가입 이름 및 닉네임 데이터 추가
Closes #263
=> Refactor : 소셜로그인 시 회원가입 데이터 수정

src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java
- 이메일 중복 체크 컨트롤러 수정
- 이메일 중복 체크 컨트롤러 @RequestParam으로 수정
- @Validated 어노테이션 추가
Closes #265
=> refactor : #265/이메일 중복 체크 컨트롤러 수정

src/main/java/org/prgrms/yas/domain/user/service/UserService.java, src/main/resources/application-prod.yml
- 소셜로그인 시 저장 데이터 변경
- 소셜로그인 시 프로필 사진 데이터로 저장하는 식으로 변경
Closes #269
=> refactor : #269/소셜로그인 시 프로필 사진 추가

src/main/java/org/prgrms/yas/domain/post/service/PostService.java, src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
- 포스팅 가능한 루틴 조회 형식 변경
- 포스팅 가능한 루틴 조회시 데이터 조건 변경
- 미션이 없는 루틴은 조회하지 않도록 변경
Closes #271
=> refactor : #271/포스팅 가능한 루틴 조회 형식 변경

src/main/java/org/prgrms/yas/domain/user/domain/User.java, src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java, src/main/java/org/prgrms/yas/domain/user/dto/UserSignUpRequest.java, src/main/java/org/prgrms/yas/domain/user/exception/NotValidPasswordException.java, src/main/java/org/prgrms/yas/global/error/ErrorCode.java, src/main/java/org/prgrms/yas/global/error/GlobalExceptionHandler.java
- 비밀번호 에러 발생시 응답 변경
- 입력 비밀번호가 일치하지 않을 시 에러 응답 구조 추가
Closes #273
=> refactor : #273/비밀번호 에러 발생시 응답 변경

src/main/java/org/prgrms/yas/domain/routine/controller/RoutineStatusController.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatusImage.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/exception/NotFoundRoutineStatusImageException.java, src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusImageRepository.java, src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java, src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
루틴완료 후 후기 작성 기능 추가
- 사진 업데이트를 위한 RoutineStatusImage 엔티티 추가 
- RoutineStatus 테이블에 emoji, content 필드 추가
- 이모지, 글, 사진 업데이트를 할 수 있다.
=> feat : #241/루틴완료 후 후기 작성 기능 추가

src/main/java/org/prgrms/yas/domain/routine/controller/RoutineStatusController.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusImageDto.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusListResponse.java, src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
루틴완료시 날짜별 전체/상세 조회, 루틴완료 상세 조회 기능 추가
- 한달 단위로 루틴완료 상세 조회 기능 추가
- 하루 단위로 루틴완료 상세 조회 기능 추가
- 루틴완료 한개에 대해 상세조회 기능 추가 (미션들까지 반환)
=> feat : #250/루틴완료시 날짜별 전체/상세 조회, 루틴완료 상세 조회 기능 추가

src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java, src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
파일이름에 uuid 추가하여 같은 이름 파일 올라와도 구분할 수 있게 처리
파일이름에 uuid 추가하여 같은 이름 파일 올라와도 구분할 수 있게 처리
=> feat : #277/파일이름에 uuid 추가하여 같은 이름 파일 올라와도 구분할 수 있게 처리

src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusCreateRequest.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java
루틴후기 작성시 컬럼명 변경 emoji -> emotion
루틴후기 작성시 컬럼명 변경 emoji -> emotion
=> refactor : #279루틴후기 작성시 컬럼명 변경 emoji -> emotion

build.gradle, src/main/resources/application.yml, src/main/resources/logback-spring.xml
- 슬랙과 로그 기록 연동
- 슬랙 비공개 채널에 에러 로그 기록되도록 연동
Closes #286
=> feat : #286/슬랙과 로그 기록 연동

src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java, src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java
- 좋아요 - 댓글 관련 하여 삭제 이슈 해결
- 좋아요가 설정되어있는 댓글 삭제시 삭제 불가능한 이슈 해결
- 좋아요삭제를 할 경우 댓글 삭제되는 이슈 해결
- Cascade 옵션 수정
Closes #282
=> fix : #282/댓글 좋아요 관련 오류 해결

src/test/java/org/prgrms/yas/config/WithMockJwtAuthentication.java, src/test/java/org/prgrms/yas/config/WithMockJwtAuthenticationSecurityContextFactory.java, src/test/resources/application.yml
- 소셜 로그인 관련 회원 통합 테스트 코드 설정 파일 수정
- yml 파일 소셜 로그인 관련하여 수정
- 불필요한 테스트 코드 토큰 필드 삭제
Closes #293
=> Fix : 소셜 로그인 관련 회원 통합 테스트 코드 설정 파일 수정

src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java, src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailStatusResponse.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java, src/main/java/org/prgrms/yas/jwt/JwtAuthenticationToken.java
미션상태 상세조회시 routineStatusId 추가
- 미션상태 상세조회시 routineStatusId 추가
=> Refactor : #297/미션상태 상세조회시 routineStatusId 추가

src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusListResponse.java
루틴완료 조회시 타임존 오류 수정
루틴완료 조회시 타임존 오류 수정
=> Fix : #300/루틴완료 조회시 타임존 오류 수정

src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java, src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java, src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java, src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java, src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java, src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java, src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java, src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusImageRepository.java, src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java, src/main/java/org/prgrms/yas/domain/user/controller/UserController.java, src/main/java/org/prgrms/yas/domain/user/domain/User.java, src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordChangeRequest.java, src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java, src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java, src/main/java/org/prgrms/yas/global/scheduler/ScheduledService.java
- 회원탈퇴 기능 추가
- 비밀번호 일치 검증을 통한 회원탈퇴 기능 추가
- 회원탈퇴를 통해 회원가입, 로그인 시 이메일 검증 기능 추가
Closes #284
=> Feat : #284/회원탈퇴 기능 추가 

src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java, src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java, src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java, src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
- 회원 탈퇴 기능 및 에러 수정
- 회원 탈퇴 간에 비밀번호 생성자 에러 수정
- 미션 및 게시물 삭제 메소드 추가
=> Feat :  #296/회원 탈퇴 기능 및 에러 수정

src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordChangeRequest.java, src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java, src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
- 테스트 관련 Dto 수정
- 테스트 관련 비밀번호 Dto 생성자 수정
Closes #307
=> Fix : #307/테스트 관련 Dto 수정

src/main/java/org/prgrms/yas/domain/routine/service/Status.java
완료한 루틴 진행시 생기는 타임존 문제 해결
완료한 루틴 진행시 생기는 타임존 문제 해결
=> Fix : #311/완료한 루틴 진행시 생기는 타임존 문제 해결

src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
루틴진행 상세조회시 루틴진행 후기 작성안했을때 조회 안되는 문제 해결
- 루틴진행 상세조회시 루틴진행 후기 작성안했을때 조회 안되는 문제 해결
- 미션완료 타임존 오류 수정
=> Fix : #312/루틴진행 상세조회시 루틴진행 후기 작성안했을때 조회 안되는 문제 해결

src/main/java/org/prgrms/yas/domain/routine/controller/RoutineStatusController.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
=> Feat : #316/루틴완료 삭제 API 추가

src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
=> Fix : #320/루틴후기 등록 오류 해결

src/main/java/org/prgrms/yas/YasApplication.java, src/main/java/org/prgrms/yas/configures/JpaAuditingConfig.java, src/test/java/org/prgrms/yas/domain/user/repository/UserRepositoryTest.java, src/test/java/org/prgrms/yas/domain/user/service/UserServiceTest.java
- 회원 Repository, Service 테스트 구현
- 메소드 수정 전, 기본적인 메소드 단위테스트 구현
Closes #296
=> Test : #296/회원 Repository, Service 테스트 구현

src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java, src/test/java/org/prgrms/yas/domain/user/service/UserServiceTest.java
- 테스트 코드 추후 수정을 위한 삭제
- 현재는 배포를 위해 잠시 테스트 코드 삭제
- 최대한 빨리 테스트 코드 수정 이후 추가 배포할 예정
=> Hotfix : 테스트 코드 추후 수정을 위한 삭제

src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
routineStatus default값 변경
routineStatus default값 변경
- emotion : 1
- content: ""
=> Refactor : #327/routineStatus default값 변경

src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDto.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
루틴후기 상세조회시 미션상태 추가
루틴후기 상세조회시 미션상태 추가
=> Refactor : #330/루틴후기 상세조회시 미션상태 추가

src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java, src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java, src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDto.java, src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java, src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
루틴후기 상세조회시 미션상태 추가
수정/추가한 내용을 적어주세요.
=> Deploy : #develop/배포

src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java, src/main/java/org/prgrms/yas/domain/user/service/UserService.java, src/main/resources/application.yml, src/test/java/org/prgrms/yas/domain/user/dto/UserDtoTest.java, src/test/java/org/prgrms/yas/domain/user/repository/UserRepositoryTest.java, src/test/java/org/prgrms/yas/domain/user/service/UserServiceTest.java
- 회원 단위 테스트 코드 수정 및 추가
- 회원 Repository 단위 테스트 코드 수정 및 추가
Closes #333
=> refactor : 회원 단위 테스트 코드 수정 및 추가
